### ISSUE TITLE
Kuorinka wordpress template multiple h1s

### ISSUE THREAD

**Issue by richarddeakin** [samikeijonen/kuorinka#18]
The Kuorinka wordpress has multiple h1s when it should have 1 max of two on each page. mainly the widgets are marked up as h1s when they should be a h2.

if you test the theme with a accessibity checker and select headings it will show which headings are marked up and what is wrong with them.
https://addons.mozilla.org/en-us/firefox/addon/accessibility-evaluation-toolb/

h1 element
    The h1 element should contain the title for the web resource and may contain the title of the website. 
    The page should contain at least one and no more than two h1 elements.

**Comment by richarddeakin** [comment]
Just for help info i work for a local governement on their websites and we get audited for accessiblity to level wcag 2.0 AA and this is a issue which has been picked up as a fail. If this is the level of accessiblity your trying to reach.

**Comment by samikeijonen** [comment]
Thanks for the feedback. I have read articles about widget titles h1 vs. h2. Only thing that's kind of bugging me is that I can't find the reason why is it right way to use h2. 

Mine decision was based on _s theme. I'll probably switch it anyways.

**Comment by richarddeakin** [comment]
Hi Sami

I think h1 is supposed to describe the page if you have multiple h1s this
would be confusing it also asks what is the point of h2 h3 if they could
all be h1s. We have accessibility consultants at our work I can ask for the
reason if you want.  I have been to work shops and seen how blind users use
a Web page and If they are taught this is how to read a Web page when your
blind it can be confusing if you decided to change how you lay out. If you
have multiple h1s they might confused into think they have moved to a new
page etc.

I will try and get back with a better definition.

Thanks

Richard

**Comment by samikeijonen** [comment]
It would be awesome if you could ask accessibility consultant and most importantly from the blind users.

**Comment by richarddeakin** [comment]
Hi

I have spoken to blind users before the consultants have blind testers as
well as other disabilities. I know this is a issue for them and we as a
government have been picked up on this in the passed and fixed so it was I
e of the things I test when building new websites.

I was asking the consultants for the specific issue definition.

I deal with website accessibility issues on a daily basis. I have signed up
to help test for WordPress templates on accessibility. Your template looks
accessible apart from this which is really  good.

Richard

**Comment by samikeijonen** [comment]
Like I said I can definitely switch widget titles to h2. And if I can get more details that's even better.

For the record I only build accessibility ready themes from now on. Kuorinka was first one that got the official tag in .org repo.

**Comment by richarddeakin** [comment]
I've emailed them for a definition and the issue it specifically causes and
any links they might have.

Your work is really good it's amazing how so many commercial themes are not
accessible it's a real nice right now. I think some of other accessible
tagged themes in wordpress having the heading issue too. I was going to try
help them also.

At work at the moment we are working on pdf accessibility. We have about
18000 pdfs on the site and 99% of rhem are not accessible the sites about
10 years old. Its a nightmare plus on going problem with the content
creators just admin never trained in office. I hate pdfs lol.

Hopefully next year we will have a new website and a new content re write
and a lot less pdfs.

Richard

**Comment by richarddeakin** [comment]
Hey not got a response from our consultants yet but I saw this blog post on
headings and advice referencing the reason for accessibility and the issue
it causes screen reader users.

http://blog.rrwd.nl/2014/11/21/html5-headings-in-wordpress-lets-fight/

**Comment by joedolson** [comment]
The most important factor for headings is whether or not there's a valid hierarchy, not a specific number or usage of heading elements. When there are too many H1 elements, the hierarchy breaks down. What I would recommend for your widget region is a .screen-reader-text H1 that heads the container for all widgets (and displays only if there are widgets in use), and H2 level headings for the widgets themselves. 

I would also recommend the same technique for your posts wrapper, and to remove the headings wrapping your site title and post title; but the most important thing is having a logical headings hierarchy. 

I wrote on this topic as well, recently: https://www.joedolson.com/2014/11/headings-hierarchy-problem/

**Comment by samikeijonen** [comment]
Thanks Joe for hopping in. That makes sense. I'll do some changes in couple of days. If you don't mind I'l ping you after I have pushed them in Github.

**Comment by samikeijonen** [comment]
P.S. Twenty fifteen is using h1 in site title in front and home page. That could also work for hierarchy.

https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfifteen/header.php#L32

**Comment by richarddeakin** [comment]
I think having a h1 as a site title duplicated on every page is confusing
for screen reader user. A bit like every page having the same page meta
title.

Other themes tagged accessibility ready so have heading issues too.

**Comment by joedolson** [comment]
I agree that having the site title as H1 is a chronic problem, and bad for usability - it's also a battle we've chosen not to fight at this time in the accessibility ready review process.

**Comment by richarddeakin** [comment]
Probably not great for seo eithier

**Comment by samikeijonen** [comment]
So using h1 for site title only in "home page" (like in twenty15) is not a good idea? I was just wondering why it's used in there.

**Comment by samikeijonen** [comment]
I pushed a lot of changes in Github.

https://github.com/samikeijonen/kuorinka/commits/master

If also pushed them in live demo: https://foxland.fi/demo/kuorinka/

It would be awesome if you could give me some feedback before I push it to .org repo. I know it's not perfect but hopefully one step for better accessibility.

**Comment by richarddeakin** [comment]
I will check it out!

**Comment by samikeijonen** [comment]
One thing puzzles me when using Firefox HeadingsMap add-on. When I check singular page like [this](https://foxland.fi/demo/kuorinka/lorem-ipsum/) I got Footer Content as "Document" main heading.

**Comment by richarddeakin** [comment]
HI Sami

it is a improvement the less important things like side widgets are no longer a <h1> which defines a structure.

I would of used section areas as h2s like side nav and the wdigets as h3s i think joedolson recomended them as h1s though i see in the comments so i see why you have done that. Part of the reason being i know this would get picked up if i used it at work and we were audited becaue this has happened in the past. But this is your theme and if we used a theme that didnt pass we would make the changes our selves.

I couldnt see document as main heading? i use this tool to look at headings under navigation heading i find it easier than headingsmap

https://addons.mozilla.org/en-us/firefox/addon/accessibility-evaluation-toolb/

**Comment by samikeijonen** [comment]
headingsmap and accessibility-evaluation-toolb tools seems to validate headings differently. 

But I trust more @joedolson experience on this than any tools. I basically changed to heading structure like he outlined [in his post](https://www.joedolson.com/2014/11/headings-hierarchy-problem/). I kind of agree with him that there can more than two h1 in page. It's more about the hierarchy, not how many h1 you have.

With that said I think every site should have accessibility check by accessibility expert, not just automated checks by machines.

**Comment by samikeijonen** [comment]
I also don't mind if we decrease heading from h1 to h2 and from h2 to h3. For example Sidebar title would become h2 and widgets inside sidebar h3. @joedolson any thoughts on this one?

**Comment by richarddeakin** [comment]
dont know why 'defines a structure' was so bold in my last post?

Automatic tools i agree help but experts are better. I dont pretend to be a expert..... just sharing my experience of yearly audits on our local gov websites.

I can ask the experts who audit our sites next week to check it if you want another set of eyes? im not in the office today. @joedolson does seem to be very knowledgeable on the subject so would apreciate his opinion too.

**Comment by joedolson** [comment]
The idea that a page should have no more than 2 H1 elements isn't something that's represented in any way by the WCAG guidelines; that's specific to the tool you're using. It may also appear in other tools, but it's not because it's actually represented directly by the guidelines. 

The reason a tool might bring up a suggestion like that has more to do with what an excess of H1 headings could be symptomatic of: a non-representational hierarchy or the usage of H1 headings for SEO reasons in places where they are not acting structurally. 

The fact is that is extremely difficult to programmatically say whether a structure is valid or not based on parsing headings - even if the structure looks OK, it requires human judgement to determine whether the usage of headings properly represents the content of the page. 

I would personally recommend keeping the H1 headings as the top level section headings for the page. This is my philosophy and my opinion, of course, but my feeling is the the document `<title>` element is what represents the page as a whole, and every H1 within the page represents a section of the document represented by the `<title>` element.

**Comment by richarddeakin** [comment]
HI Joe

I only suggested it should have a max of two because we have had always to comply to that in our accessiblity audits. We have always been advised to have 1 <h1> im not sure how a second one could be useful really?? if limiting it to two.

We are supposed to be audited to wcag 2.0 AA by DAC http://www.digitalaccessibilitycentre.org/ but that is aways subjective i guess. I have seen visualy impaired users test our site and even tried it myself  (Blindfolded) and seen the difficulties a user faces. The visually imapired users who test our site might have been taught how to navigate expecting only a max of 2 <h1>s so knowing any different would be hard for them. So the use of more than 2 <h1>s could be a uk thing or limited to DAC or Shawtrust as we used to use them. I deffintely don't pretent to know how univserally headings are used by viually impaired users.

I would say that if they are staying <h1>s the main body <h1> should be the first one called because they tab throught the headings to hear each one and if the main body will be the only unique one which it would be as the rest are reapeated on every page, It would makes it easier to listen out for and not miss. This is probably why we are told at work to use a sole <h1> because its the most important heading unlike "footer content" which is rarely used. Its a bit like the skip nav link to miss out all the repetitive links, they want to get to the main content easily.

I do see the page title representing the page as a whole, i think the <h1> shows the user where to start i guess.

I think your deffintely technically more knowledge able than me Joe! i just have to work to the standards DAC set us at work so thats all i know.

**Comment by richarddeakin** [comment]
i think where i marked things has <h  1  > it has made things headings ohps sorry.

**Comment by joedolson** [comment]
For the record, if you surround code examples in backticks (same key as the tilde on a standard keyboard), they'll show as code rather than being rendered in the email. 

The standards an audit holds you to and the actual reality of guidelines or practical accessibility are always different. Heading navigation works by jumping from heading to heading, and that can be done between equal or different levels of headings. No matter how the hierarchy is set up, the user ultimately has to learn the hierarchy for a given site. 

For the record, DAC isn't consistent on their own site - they have an invalid hierarchy on the home page and have 4 H1 headings on their blog page. I'm highly dubious about a requirement that's specifically for two H1 headings -- one would make some sense, multiple makes sense, but specifically two? That's oddly arbitrary, to me.

**Comment by samikeijonen** [comment]
@richarddeakin What would be really helpful is to give visually impaired users test the site and give insight how they can navigate. They are the real experts. I use to have almost blind student but she's graduated now so I can't ask her to test sites for me:)

Anyways I can understand this heading debate is never going to end. I might go with the safest bet and turn h1 to h2 and h2 to h3. That can't wrong either.

**Comment by joedolson** [comment]
Yep. It's a circular argument, really - that's the reason that we don't require a *specific* headings hierarchy in the WP theme accessibility guidelines. From a practical perspective for the screen reader user, the key is that there *are* headings and that they reflect the sections they head. Otherwise, it's details of usability that may just be specific to the user.

**Comment by samikeijonen** [comment]
Huge thanks for both of you for this conversation! This has been one learning step for me.

**Comment by richarddeakin** [comment]
im very new to github! thanks

yeah i dont get why 2 h1s on the automatic tools eithier i couldnt logical think how you could order the content.

I think DAC had a recent update on their site so the multiple h1s might of slipped in! i will feedback to them though. Every time we have a update on our main site something usually brakes else where.

I should be able to ask DAC to test it for us with visually impaired users next week when back in the office.

We have contracts with suppliers of software when having anything built for us to wcag 2.0 AA and the suplier aways as a differrent interpritation to what that is to who tests it. 

i have enjoyed the discussion too! its brillinat you value the importance

**Comment by samikeijonen** [comment]
I decided to switch h1 to h2 and h2 to h3. You can see the the [commits here](https://github.com/samikeijonen/kuorinka/commits/master).

I might have missed something so eny feedback is welcome. I also pushed the updates in .org repo.

**Comment by richarddeakin** [comment]
That's great I will check it out.

**Comment by samikeijonen** [comment]
Gonna close this for now.
